"""initial migration

Revision ID: 1084b285cc87
Revises: 38b45958740e
Create Date: 2015-04-11 20:56:45.632863

"""

# revision identifiers, used by Alembic.
revision = '1084b285cc87'
down_revision = '38b45958740e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blank_fill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('difficult_level', sa.Float(), nullable=True),
    sa.Column('add_date', sa.Date(), nullable=True),
    sa.Column('faq', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('knowledge_points', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('single_choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('difficult_level', sa.Float(), nullable=True),
    sa.Column('add_date', sa.Date(), nullable=True),
    sa.Column('faq', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('knowledge_points', sa.Integer(), nullable=True),
    sa.Column('answer', sa.Enum('A', 'B', 'C', 'D'), nullable=True),
    sa.Column('A', sa.String(length=255), nullable=True),
    sa.Column('B', sa.String(length=255), nullable=True),
    sa.Column('C', sa.String(length=255), nullable=True),
    sa.Column('D', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('essay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('difficult_level', sa.Float(), nullable=True),
    sa.Column('add_date', sa.Date(), nullable=True),
    sa.Column('faq', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('knowledge_points', sa.Integer(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('essay')
    op.drop_table('single_choice')
    op.drop_table('blank_fill')
    ### end Alembic commands ###
