"""initial migration

Revision ID: 11476b3710c2
Revises: 43423d0c04d8
Create Date: 2015-04-06 00:54:36.929569

"""

# revision identifiers, used by Alembic.
revision = '11476b3710c2'
down_revision = '43423d0c04d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
