"""initial migration

Revision ID: 127a81d13b35
Revises: 8e2d1b68f43
Create Date: 2015-04-05 14:49:57.932167

"""

# revision identifiers, used by Alembic.
revision = '127a81d13b35'
down_revision = '8e2d1b68f43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
