"""initial migration

Revision ID: 12b46f9f5af5
Revises: 11476b3710c2
Create Date: 2015-04-06 15:00:02.266646

"""

# revision identifiers, used by Alembic.
revision = '12b46f9f5af5'
down_revision = '11476b3710c2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blank_fill', 'score')
    op.drop_column('essay', 'score')
    op.drop_column('single_choice', 'score')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('single_choice', sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('essay', sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('blank_fill', sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
