"""initial migration

Revision ID: 18c829baf40
Revises: 3af8b1b12c7c
Create Date: 2015-04-02 19:31:47.859678

"""

# revision identifiers, used by Alembic.
revision = '18c829baf40'
down_revision = '3af8b1b12c7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('difficult_level', sa.Enum('A', 'B', 'C', 'D', 'E'), nullable=True),
    sa.Column('add_date', sa.DateTime(), nullable=True),
    sa.Column('faq', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blank_fill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('difficult_level', sa.Enum('A', 'B', 'C', 'D', 'E'), nullable=True),
    sa.Column('add_date', sa.DateTime(), nullable=True),
    sa.Column('faq', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'single_choice', sa.Column('difficult_level', sa.Enum('A', 'B', 'C', 'D', 'E'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'single_choice', 'difficult_level')
    op.drop_table('blank_fill')
    op.drop_table('essay')
    ### end Alembic commands ###
