"""initial migration

Revision ID: 1b749564871d
Revises: c6e43a5c145
Create Date: 2015-05-12 08:01:18.353517

"""

# revision identifiers, used by Alembic.
revision = '1b749564871d'
down_revision = 'c6e43a5c145'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
