"""initial migration

Revision ID: 25f61151650c
Revises: 48d34ea52bfc
Create Date: 2015-04-09 23:59:24.557779

"""

# revision identifiers, used by Alembic.
revision = '25f61151650c'
down_revision = '48d34ea52bfc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blank_fill', sa.Column('knowledge_points', sa.String(length=255), nullable=True))
    op.add_column('essay', sa.Column('knowledge_points', sa.String(length=255), nullable=True))
    op.add_column('single_choice', sa.Column('knowledge_points', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('single_choice', 'knowledge_points')
    op.drop_column('essay', 'knowledge_points')
    op.drop_column('blank_fill', 'knowledge_points')
    ### end Alembic commands ###
