"""initial migration

Revision ID: 2fe055aaced0
Revises: 4876ca7c6da1
Create Date: 2015-04-14 11:47:22.911722

"""

# revision identifiers, used by Alembic.
revision = '2fe055aaced0'
down_revision = '4876ca7c6da1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Points')
    ### end Alembic commands ###
