"""initial migration

Revision ID: 33daf6cd97e5
Revises: 1ce02e4ebef9
Create Date: 2015-04-14 16:00:35.220071

"""

# revision identifiers, used by Alembic.
revision = '33daf6cd97e5'
down_revision = '1ce02e4ebef9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blank_fill', sa.Column('subject_name', sa.String(length=127), nullable=True))
    op.add_column('essay', sa.Column('subject_name', sa.String(length=127), nullable=True))
    op.add_column('single_choice', sa.Column('subject_name', sa.String(length=127), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('single_choice', 'subject_name')
    op.drop_column('essay', 'subject_name')
    op.drop_column('blank_fill', 'subject_name')
    ### end Alembic commands ###
