"""initial migration

Revision ID: 38b45958740e
Revises: 25f61151650c
Create Date: 2015-04-11 20:47:56.905660

"""

# revision identifiers, used by Alembic.
revision = '38b45958740e'
down_revision = '25f61151650c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
