"""initial migration

Revision ID: 3aeeee004af7
Revises: 127a81d13b35
Create Date: 2015-04-05 15:16:33.690969

"""

# revision identifiers, used by Alembic.
revision = '3aeeee004af7'
down_revision = '127a81d13b35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blank_fill', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('essay', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('single_choice', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('single_choice', 'timestamp')
    op.drop_column('essay', 'timestamp')
    op.drop_column('blank_fill', 'timestamp')
    ### end Alembic commands ###
