"""initial migration

Revision ID: 3af8b1b12c7c
Revises: None
Create Date: 2015-04-02 19:16:30.191367

"""

# revision identifiers, used by Alembic.
revision = '3af8b1b12c7c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('single_choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Enum('A', 'B', 'C', 'D'), nullable=True),
    sa.Column('add_date', sa.DateTime(), nullable=True),
    sa.Column('A', sa.String(length=64), nullable=True),
    sa.Column('B', sa.String(length=64), nullable=True),
    sa.Column('C', sa.String(length=64), nullable=True),
    sa.Column('D', sa.String(length=64), nullable=True),
    sa.Column('faq', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('single_choice')
    ### end Alembic commands ###
