"""initial migration

Revision ID: 41c52aba5363
Revises: 18c829baf40
Create Date: 2015-04-05 13:53:07.793668

"""

# revision identifiers, used by Alembic.
revision = '41c52aba5363'
down_revision = '18c829baf40'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('essay', sa.Column('answer', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('essay', 'answer')
    ### end Alembic commands ###
