"""initial migration

Revision ID: 42e8a0643552
Revises: 476fd0e40f04
Create Date: 2015-04-22 19:06:26.934142

"""

# revision identifiers, used by Alembic.
revision = '42e8a0643552'
down_revision = '476fd0e40f04'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_paper', sa.Column('add_date', sa.Date(), nullable=True))
    op.add_column('test_paper', sa.Column('difficult_level', sa.Float(), nullable=True))
    op.add_column('test_paper', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_paper', 'timestamp')
    op.drop_column('test_paper', 'difficult_level')
    op.drop_column('test_paper', 'add_date')
    ### end Alembic commands ###
