"""initial migration

Revision ID: 43423d0c04d8
Revises: c8a3cb87332
Create Date: 2015-04-05 21:49:05.094070

"""

# revision identifiers, used by Alembic.
revision = '43423d0c04d8'
down_revision = 'c8a3cb87332'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blank_fill', sa.Column('faq_html', sa.Text(), nullable=True))
    op.add_column('blank_fill', sa.Column('question_html', sa.Text(), nullable=True))
    op.add_column('essay', sa.Column('answer_html', sa.Text(), nullable=True))
    op.add_column('essay', sa.Column('faq_html', sa.Text(), nullable=True))
    op.add_column('essay', sa.Column('question_html', sa.Text(), nullable=True))
    op.add_column('single_choice', sa.Column('faq_html', sa.Text(), nullable=True))
    op.add_column('single_choice', sa.Column('question_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('single_choice', 'question_html')
    op.drop_column('single_choice', 'faq_html')
    op.drop_column('essay', 'question_html')
    op.drop_column('essay', 'faq_html')
    op.drop_column('essay', 'answer_html')
    op.drop_column('blank_fill', 'question_html')
    op.drop_column('blank_fill', 'faq_html')
    ### end Alembic commands ###
