"""initial migration

Revision ID: 43afe93d3788
Revises: 4af7bebc7b8e
Create Date: 2015-04-22 21:08:35.241804

"""

# revision identifiers, used by Alembic.
revision = '43afe93d3788'
down_revision = '4af7bebc7b8e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_paper', sa.Column('subject', sa.Integer(), nullable=True))
    op.add_column('test_paper', sa.Column('subject_name', sa.String(length=127), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_paper', 'subject_name')
    op.drop_column('test_paper', 'subject')
    ### end Alembic commands ###
