"""initial migration

Revision ID: 4874d58c818
Revises: 2fe055aaced0
Create Date: 2015-04-14 15:13:51.820492

"""

# revision identifiers, used by Alembic.
revision = '4874d58c818'
down_revision = '2fe055aaced0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Points')
    op.add_column(u'blank_fill', sa.Column('subject', sa.Integer(), nullable=True))
    op.add_column(u'essay', sa.Column('subject', sa.Integer(), nullable=True))
    op.add_column(u'single_choice', sa.Column('subject', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'single_choice', 'subject')
    op.drop_column(u'essay', 'subject')
    op.drop_column(u'blank_fill', 'subject')
    op.create_table('Points',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=127), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('subject')
    op.drop_table('points')
    ### end Alembic commands ###
