"""initial migration

Revision ID: 4876ca7c6da1
Revises: 1084b285cc87
Create Date: 2015-04-11 22:11:51.440566

"""

# revision identifiers, used by Alembic.
revision = '4876ca7c6da1'
down_revision = '1084b285cc87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
