"""initial migration

Revision ID: 8e2d1b68f43
Revises: 41c52aba5363
Create Date: 2015-04-05 14:42:49.030881

"""

# revision identifiers, used by Alembic.
revision = '8e2d1b68f43'
down_revision = '41c52aba5363'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
