"""initial migration

Revision ID: a47c9c28e72
Revises: 33daf6cd97e5
Create Date: 2015-04-14 21:01:36.661916

"""

# revision identifiers, used by Alembic.
revision = 'a47c9c28e72'
down_revision = '33daf6cd97e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('subject', sa.Integer(), nullable=True))
    op.add_column('points', sa.Column('subject_name', sa.String(length=127), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'subject_name')
    op.drop_column('points', 'subject')
    ### end Alembic commands ###
