"""initial migration

Revision ID: c6e43a5c145
Revises: 43afe93d3788
Create Date: 2015-04-23 17:28:01.935319

"""

# revision identifiers, used by Alembic.
revision = 'c6e43a5c145'
down_revision = '43afe93d3788'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_paper', 'difficult_level')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_paper', sa.Column('difficult_level', mysql.FLOAT(), nullable=True))
    ### end Alembic commands ###
