"""initial migration

Revision ID: c8a3cb87332
Revises: 3aeeee004af7
Create Date: 2015-04-05 20:57:49.897058

"""

# revision identifiers, used by Alembic.
revision = 'c8a3cb87332'
down_revision = '3aeeee004af7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
